# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LonganApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinindustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('industry_id', models.IntegerField()),
            ],
            options={
                'db_table': 'cinIndustry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'favorites',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prefers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
                ('industry_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'prefers',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='prefers',
            unique_together=set([('industry_name', 'email')]),
        ),
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together=set([('company_name', 'email')]),
        ),
    ]
