# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LonganApp', '0003_auto_20170423_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='latitude',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='longitude',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
